# Generated by Django 4.2 on 2024-04-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skatepark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200, verbose_name='UCCS Email')),
                ('difficulty', models.CharField(blank=True, choices=[('Beginner', '1'), ('Easy', '2'), ('Medium', '3'), ('Hard', '4'), ('Extreme', '5')], max_length=200)),
            ],
        ),
    ]
