# Generated by Django 4.2 on 2024-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatepark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skatepark',
            name='Location',
            field=models.CharField(max_length=200, verbose_name='Location:'),
        ),
        migrations.AlterField(
            model_name='skatepark',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Extreme')], max_length=200),
        ),
    ]
