# Generated by Django 4.2 on 2024-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatepark_app', '0003_alter_skatepark_difficulty_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skatepark',
            old_name='Location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='skatepark',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Easy', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Extreme')], max_length=200),
        ),
    ]
