# Generated by Django 4.2 on 2024-04-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatepark_app', '0005_alter_skatepark_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='skatepark',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
