# Generated by Django 4.2 on 2024-04-19 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skatepark_app', '0007_skater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='park',
        ),
        migrations.AddField(
            model_name='review',
            name='skatepark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skatepark_app.skatepark'),
        ),
    ]
