# Generated by Django 4.2 on 2024-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skatepark_app', '0009_skatepark_latitude_skatepark_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, max_length=5),
            preserve_default=False,
        ),
    ]
